#!/usr/bin/env node
// Regenerate the generated parts of the agent skill:
//   - skills/hey-axi/references/commands.md, from src/manifest.json, src/policy.js, src/shape.js
//   - the home-view block in skills/hey-axi/SKILL.md, from src/guide.js (the same text
//     `hey-axi` prints with no arguments, so the skill never drifts from the CLI)
// Command examples are written as `npx -y hey-axi ...`, so they run even when the skill is
// installed without hey-axi on PATH.
//
//   npm run skill:gen      # write
//   npm run skill:check    # exit 1 if anything is stale (CI)

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { loadBundledManifest, listCommands } from "../src/router.js";
import { checkPolicy, runMode, sendStaging } from "../src/policy.js";
import { DETAIL_FIELDS, LIST_FIELDS, parseField } from "../src/shape.js";
import { DESCRIPTION, HOME_HELP } from "../src/guide.js";

export const REFERENCE_PATH = fileURLToPath(new URL("../skills/hey-axi/references/commands.md", import.meta.url));
export const SKILL_PATH = fileURLToPath(new URL("../skills/hey-axi/SKILL.md", import.meta.url));

function note(path) {
  const none = new Set();
  const env = {};
  const tty = { stdin: true, stdout: true };
  if (sendStaging(path, none, env)) return "saved as a draft unless `--allow-send`";
  const refusal = checkPolicy(path, none, env, tty);
  if (refusal?.error === "send blocked") return "refused unless `--allow-send`";
  if (refusal?.error === "secret output blocked") return "refused unless `--allow-secret`";
  const mode = runMode(path, none);
  if (mode === "interactive") return "needs a person: refused unless --interactive";
  if (mode === "stream") return "streams events (TOON; --json for NDJSON)";
  if (mode === "raw") return path === "timetrack export" ? "raw CSV unless `--output <file>`" : "raw output";
  const fields = LIST_FIELDS[path] || DETAIL_FIELDS[path];
  return fields ? `fields: ${fields.map((spec) => parseField(spec).key).join(", ")}` : "";
}

const esc = (text) => String(text).replace(/\|/g, "\\|");

// The skill's command form: runnable without a global install.
export const NPX = "npx -y hey-axi";
const npx = (text) => text.replace(/`hey-axi /g, `\`${NPX} `);

export function renderReference(manifest = loadBundledManifest()) {
  const commands = listCommands(manifest.commands);
  const lines = [
    "# hey-axi command reference",
    "",
    `<!-- Generated by scripts/gen-skill.js from src/manifest.json (hey ${manifest.hey_version}). Do not edit by hand. -->`,
    "",
    `Every command from HEY CLI ${manifest.hey_version} (${commands.length} runnable paths, including the \`login\`/\`logout\` aliases and shortcut forms such as \`box <name>\`). Run each as \`${NPX} <command> [args] [flags]\` (just \`hey-axi …\` when it is installed globally).`,
    `\`${NPX} <command> --help\` shows usage, arguments, every flag with its default, 2-3 examples and notes, offline.`,
    "Flags every command accepts: `--account <id|all>`, `--json`, `--quiet`, `--fields <a,b|all>`, `--full`, `--ids-only`, `--count`, `--markdown`, `--html`, `--styled`, `--jq <expr>`. Unknown commands, flags and arguments, flags without a value and values of the wrong type are rejected before HEY runs (exit 2).",
    "",
    "| Command | What it does | Flags | hey-axi behavior |",
    "|---|---|---|---|",
  ];
  for (const node of [...commands].sort((a, b) => a.path.split(" ")[0].localeCompare(b.path.split(" ")[0]))) {
    const flags = (node.flags || []).map((flag) => `\`--${flag.name}${flag.value ? " <v>" : ""}\``).join(" ");
    lines.push(`| \`${node.path}\` | ${esc(node.short)} | ${flags} | ${note(node.path)} |`);
  }
  return lines.join("\n") + "\n";
}

const START = "<!-- generated:home:start -->";
const END = "<!-- generated:home:end -->";

export function renderSkill(current = readFileSync(SKILL_PATH, "utf8")) {
  const block = [
    START,
    "<!-- Generated by scripts/gen-skill.js from src/guide.js, the same text the home view prints. Do not edit by hand. -->",
    `What hey-axi is: ${DESCRIPTION}`,
    "",
    "Next steps the home view suggests:",
    ...HOME_HELP.map((line) => `- ${npx(line)}`),
    END,
  ].join("\n");
  return current.replace(new RegExp(`${START}[\\s\\S]*?${END}`), block);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const targets = [[REFERENCE_PATH, renderReference()], [SKILL_PATH, renderSkill()]];
  if (process.argv.includes("--check")) {
    const stale = targets.filter(([path, content]) => readFileSync(path, "utf8") !== content).map(([path]) => path);
    if (stale.length) {
      console.error(`stale: ${stale.join(", ")}\nrun \`npm run skill:gen\` and commit the result`);
      process.exit(1);
    }
    console.log("skill files are up to date");
  } else {
    for (const [path, content] of targets) writeFileSync(path, content);
    console.log(`wrote ${targets.map(([path]) => path).join(", ")}`);
  }
}
